### ISSUE TITLE
Syntax errors & other small problems

### ISSUE THREAD

**Issue by nick-iris** [PIC-IRIS/PH5#1]
Below is a list of syntax errors and other problems that I have found in some of the PH5 scripts.

- "BREAK_STANDARD" variable is undefined
https://github.com/PIC-IRIS/PH5/blob/master/webservices/SEGYFactory.py#L1149
- "forget_das_t" method should have _self_ as first parameter
https://github.com/PIC-IRIS/PH5/blob/master/webservices/ph5API.py#L589-L591
- "math" module is referenced but not imported
https://github.com/PIC-IRIS/PH5/blob/master/webservices/ph5API.py#L950-L959
- "Offset" variable is undefined
https://github.com/PIC-IRIS/PH5/blob/master/webservices/ph5torec.py#L230
- Line references system specific path. Causes script to not run on other systems.
https://github.com/PIC-IRIS/PH5/blob/master/webservices/ph5torec.py#L9
- Line references system specific path. Causes script to not run on other systems.
https://github.com/PIC-IRIS/PH5/blob/master/webservices/ph5toevt.py#L9
- "os" module is referenced but not imported
https://github.com/PIC-IRIS/PH5/blob/master/webservices/columns.py#L713
- "TIME_TYPE" variable is undefined
https://github.com/PIC-IRIS/PH5/blob/master/webservices/columns.py#L755

**Comment by rsdeazevedo** [comment]
Nick, i fixed and pushed items 1, 2, 3, 6, 7, 8. I will leave the items related to ph5torec until i push a version that is closer to being completed.
