### ISSUE TITLE
ph5tostationxml.py response level requests do not return response information

### ISSUE THREAD

**Issue by nick-iris** [PIC-IRIS/PH5#11]
Response level requests made to ph5tostationxml.py currently do not return any response level information. I believe this was because response info is being stored in PH5 as RESP files, and there is no easy way to read RESP files in Python.

What is the current status of this? Last I remember hearing was that a developer at the PIC had developed a library for this purpose, and was going to add it to ObsPy for the upcoming release.

**Comment by derick-hess** [comment]
I'll talk to LLoyd tomorrow. I know it is ready to go for everything but nodes and that code is slated to be in the next Obspy release.  LLoyd was finishing up code to work for the nodes(or any other all in one unit where the sensor and datalogger don't have separate response information)

**Comment by nick-iris** [comment]
Do you know what ObsPy GitHub issue LLoyd's code is under?

**Comment by rsdeazevedo** [comment]
Lloyd;

Can you answer Nick?

Thanks.

**Comment by nick-iris** [comment]
I found it. ObsPy issue 1185. Thanks.

**Comment by dsentinel** [comment]
Glad you found it. If you have any questions feel free to ask. --Lloyd

**Comment by nick-iris** [comment]
This is working with a developmental ObsPy 1.1.0 install, so I'm closing this issue.
