### ISSUE TITLE
Issue with ph5tostationxml.py handling empty location codes

### ISSUE THREAD

**Issue by nick-iris** [PIC-IRIS/PH5#14]
@rsdeazevedo @derick-hess 

__Issue description__
After we updated the Seisorz experiment to correctly store empty string location codes, instead of `"--"`, I found a problem with the way the Web Services pass empty location codes to the _ph5tostationxml.py_ API.

The problem was caused because there is not a reliable way, that I know of, to represent empty-string location codes in  a comma separated string. This issue makes it impossible to request the Seisorz experiment that contains only empty location codes, as the PH5toStationXML class expects comma separated strings for location values.

__Fixing the issue required some small changes to ph5tostationxml.py__:
-  I changed the `network_list`, `reportnum_list`, `sta_list`, `array_list`, `location_list`, `channel_list` and `ph5path` parameters in _ph5tostationxml.py_ to expect a Python List object instead of a comma separated string of values.  
- I moved related conversions from comma separated strings to Python List objects to the `__main__` method of _ph5tostationxml.py_, and out of the `PH5toStationXML` class. This way the ability to use the program as a command line application should remain unchanged.

If it is okay with both of you, I am going to submit a pull request with my changes.

Thanks,
Nick

**Comment by derick-hess** [comment]
that sounds like a reasonable solution to me.
