### ISSUE TITLE
RESP upload utility needs to be added

### ISSUE THREAD

**Issue by nick-iris** [PIC-IRIS/PH5#150]
There is a great need for a RESP upload utility. Currently we have been receiving experiments from PIs without RESP information, and @derick-hess has been adding this info for them. This works as a temporary solution, but makes it so that outside users cannot use all of the extraction programs before sending us their data. For example ph5tostationxml.py will not work without the RESP info.

**Comment by derick-hess** [comment]
Resp_load has already been developed and added PR #136

**Comment by derick-hess** [comment]
I do need to add some instructions. Also, I will contact our data group and see if the long doc and new ph5 in a nutshell is reayd so I can link to them on the github

**Comment by nick-iris** [comment]
Thats great thanks Derick!
