### ISSUE TITLE
ph5tostationxml text format results in error

### ISSUE THREAD

**Issue by nick-iris** [PIC-IRIS/PH5#181]
The command line version of ph5tostationxml is resulting in the following error whenever the text format is requested.

```
(ph5) -bash-4.1$ ph5tostationxml -p . -n master.ph5 --level=network -f TEXT --network=*
Error - Unable to write stationtxt at channel level. One or more networks contain no stations. Using `level='network'` might work (with less detail in the output).
```

**Comment by derick-hess** [comment]
this error seems to becoming from inv.write like maybe the stationtxt writer wherever that is requires channels. I don't think this error is in ph5tosdtationxml, but I'll look more closely.
