### ISSUE TITLE
nuke_table should have an option to delete all arrays

### ISSUE THREAD

**Issue by nick-iris** [PIC-IRIS/PH5#213]
The `nuke_table` command should have an option to remove all arrays since ph5tokef has a option called `--all_arrays` which dumps all of the array metadata to a kef file. Currently users must specify individual arrays.

This would allow users to dump all array metadata using ph5tokef, make any edits, use nuke_table to remove the old array metadata in one step, and then use keftoph5 to load all of the array data.

**Comment by derick-hess** [comment]
I agree. That should be an easy addition. I'll get someone assigned to it.

**Comment by nick-iris** [comment]
Awesome thanks!
