### ISSUE TITLE
Modules should not call sys.exit()

### ISSUE THREAD

**Issue by nick-falco** [PIC-IRIS/PH5#215]
There are lots of places where modules call `sys.exit()`. This is considered a poor practice, as it can lead to unexpected behavior. Take for example the scenario where the PH5 api is being used in a server environment. Calling `sys.exit()` could crash the entire server.

Instead of calling `sys.exit()`, modules should be raising exceptions and catching them at a higher level.

**Comment by derick-hess** [comment]
@damhuonglan as an example; in ph5_merge_helper.py all of the sys.exit() calls should eb removed and instead raise an exception and then those exceptions should be caught in main()

**Comment by derick-hess** [comment]
also make sure not to add things like below to files.
```
################################################################
#
# modification
# version: 2019.032
# author: Lan Dam
# When multiple days are request, cut on day boundaries instead of
# every 24 hours
```

**Comment by ascire-pic** [comment]
Closing this issue due to beginning development of GeoHDF
