### ISSUE TITLE
Commented out code should be removed

### ISSUE THREAD

**Issue by nick-iris** [PIC-IRIS/PH5#216]
Lots of the modules have commented out code that should be removed. This code will still be in source control once removed, so you are not gaining anything by keeping it in the code.

**Comment by nick-iris** [comment]
@derick-hess Are you okay with me going through the codebase and removing old commented out code?

**Comment by derick-hess** [comment]
Yeah that's a good idea.

**Comment by nick-iris** [comment]
Okay I'll make these changes on the `cleanup` branch.

**Comment by derick-hess** [comment]
okay thanks. I'l start addressing the other issues on monday morning when I get back in the office. I've been on a trip to Woods Hole this week

**Comment by nick-iris** [comment]
Okay perfect. Perhaps review the changes I make on the `cleanup` branch first so that we don't run into merge conflicts.
