### ISSUE TITLE
Modules should be updated to not use global variables

### ISSUE THREAD

**Issue by nick-falco** [PIC-IRIS/PH5#218]
There a lots of older modules, such as `report_gen.py` and `recreate_external_references.py`, that use global variables everywhere to pass around state. These should be updated so that global variables are not used, as they make debugging more difficult and the code more fragile.

**Comment by derick-hess** [comment]
Global variables that are okay are things like
PH5VERSION 
PROG_VERSION 
LOGGER = logging.getLogger(__name__)

**Comment by ascire-pic** [comment]
Closing this issue due to beginning development of GeoHDF
