### ISSUE TITLE
sort_kef_gen should have an option to write to a file

### ISSUE THREAD

**Issue by nick-iris** [PIC-IRIS/PH5#220]
Currently `sort_kef_gen.py` does not have an option to write to a file. By default it only writes to `stdout`, which blows up the terminal.

It should have something like this:
``` python
parser.add_argument("-o", "--outfile", action="store",
                    help=("KEF file write /Experiment_g/Sorts_g/Sort_t entries to. "
                               "Defaults to stdout."),
                    default=sys.stdout)
```

**Comment by derick-hess** [comment]
Thanks . A few other tools do that and expect you to pipe the output to a file. I'll fix them all at once

**Comment by nick-iris** [comment]
I have a major commit that I will push tomorrow. It includes a complete overhaul of the way logging is handled as well as some smaller fixes.

**Comment by nick-iris** [comment]
`tabletokef` also need this option.

**Comment by derick-hess** [comment]
@damhuonglan sort_kef_gen tabletokef and time_kef_gen. Currently output their kef files directly to stdout. Instead they need to write their output to a file.

I will get you a small  ph5 archive to test against and show you how they currently work.
