### ISSUE TITLE
experiment_t_gen window too big for some OS's

### ISSUE THREAD

**Issue by dthomas1953** [PIC-IRIS/PH5#232]
We are making a new generation of laptops for PIs. These are based on inexpensive Dell Windows 10 laptops (Dell Latitude 3490).
We have deployed Centos 7.5 on these laptops, and it's running most of our PASSCAL software suite with no problems. 

On PH5, however, when we get to experiment_t_gen, there's no way to get to the "Generate Kef" button. The bottom of the GUI window is clipped, and there's no way to move anything to get there. Changing screen resolution doesn't help, they're already at highest res.
![experiment-t-gen-prob](https://user-images.githubusercontent.com/42277951/49050594-58fffc00-f1a1-11e8-8a5b-5c2d365495df.png)

Here's how it looks normally:
![experiment_t_gen_ok](https://user-images.githubusercontent.com/42277951/49050585-4d143a00-f1a1-11e8-974f-1f8bb1d18fba.png)

Solutions might include a smaller window overall, resizable windows, buttons at the top of the form, etc.

**Comment by derick-hess** [comment]
This will be going away and a simplified version will be built in to the new PH5 GUI
