### ISSUE TITLE
pforma: UTM Zone setting doesn't 'stick'

### ISSUE THREAD

**Issue by dthomas1953** [PIC-IRIS/PH5#233]
When in pforma, after setting the UTM Zone, if you pull up the dropdown for UTM again, it always says "1" for the zone. 

More of a minor nuisance rather than a serious problem. The output files do show which UTM zone was used, e.g.
```
location/description_s=Converted from UTM Zone 58
```
It would be more re-assuring to users if pforma could 'remember' the UTM zone setting for display.

**Comment by derick-hess** [comment]
addressed in pr #237
