### ISSUE TITLE
pforma never completes display

### ISSUE THREAD

**Issue by dthomas1953** [PIC-IRIS/PH5#234]
We've had problems with the latest release on several platforms. pforma never gets past the 'kill' displays, it just sits there. Looking at file accumulation, the files (about 694MB for our dataset) are accumulating as expected in the folder, but pforma never gets to its closure. So, things are being written to PH5 and subfolders, but without closure.

I have been testing old versions, and the error exists all the way back to commit# 88e5349 on Sept. 27th 2018.

The Sept. 25th version (Commit # a3c98ac) works well, pforma runs well, as do responses/etc.

**Comment by derick-hess** [comment]
Adressed in pr #237
