### ISSUE TITLE
ph5tostationxml.py not filtering at the appropriate level of granularity

### ISSUE THREAD

**Issue by nick-iris** [PIC-IRIS/PH5#25]
ph5tostationxm.pyl is only filtering results to the level of granularity defined by the "level" query argument.

The ph5tostationxml.py program should always filter at the channel level, regardless of the "level" argument. The "level" argument only should define what level of detail the returned StationXML/Text contains, not what level to filter results. 

Example:
The request with channel="bad" at level=station returns data when it should not:
http://service.iris.edu/ph5beta/station/1/query?channel=bad&level=station&nodata=404

However for level=channel this request correctly returns no-data, because the channel query argument is now being enforced:
http://service.iris.edu/ph5beta/station/1/query?channel=bad&level=channel&nodata=404

Let me know if you have any questions.

**Comment by derick-hess** [comment]
This shouldn't take too much. Removing the check variables and a few small changes ot the loop should be all that's needed. I'll get on this tomorrow morning.
