### ISSUE TITLE
ph5toms not returning data when it should

### ISSUE THREAD

**Issue by nick-iris** [PIC-IRIS/PH5#255]
The following request no longer returns any data after the query das table changes:

`ph5toms -n master.ph5 -p /hdf5-data2/PH5_Experiments/pn4/16-015/ --network=YW --starttime=2016-06-21T16:43:58.0 --stoptime=2016-06-21T16:43:59.0 --station=1001`

**Comment by derick-hess** [comment]
Thanks Nick I'll check it out.
