### ISSUE TITLE
[BUG] dumpfair IOError: [Errno 32] Broken pipe

### ISSUE THREAD

**Issue by jschaeff** [PIC-IRIS/PH5#270]
**Describe the bug**
dumpfair raise an error "Broken pipe". Note that the program seems to work correctly otherwise. Expected result seems OK.

**Environment (please complete the following information):**
 - OS: Centos 7
 - Program Version ph5 4.1.1
**To Reproduce**
The error happens before the rest of the output. To see it clearly:
$ dumpfair 10.0.0.fcnt | head -1

**Expected behavior**
No "Broken pipe" error.

**Comment by derick-hess** [comment]
@jschaeff Thanks. I will post a fix top this shortly. By default python automatically traps SIGPIPE and translates it into an IO error and terminates. I will update dumpfair to ignore SIGPIPE and allow it to write out in the way intended.
