### ISSUE TITLE
Unit Tests Needed

### ISSUE THREAD

**Issue by derick-hess** [PIC-IRIS/PH5#282]
Now that building a test data set has been added to PH5, more unit tests can be developed. 
I am going to add a checklist below to keep track of what packages have unit tests.  Refer to this issue when adding a PR that adds unit tests and check off the package that you have added unit tests for.  When unit tests have been created for all packages this issue can be closed. 

Please don't check off a package until the unit tests cover as much of the package as possible. You can use the python package Coverage to check.  To check form command line in PH5 main directory run `coverage run runtests.py`
from there you can either use `coverage report` or `coverage html` 
coverage html is nice because it creates a directory called htmlcov.  Just open index.html and you can navigate to anything the tests cover and see what lines of code and not covered. There is no hard rule for cover % for the tests, but make sure they test the code well. Test expected normal inputs, bad inputs as well as atypical inputs.  Update the code if needed to make sure inputs both good and bad are handled gracefully.

In order to test main() methods in most code you will need to update the way get_args is handled. Look at metadatatoph5 and test_metadatatoph5 as an example for how to accomplish this. 

Clients
- [x] ph5availability
- [ ] ph5toevt
- [ ] ph5torec
- [ ] ph5toexml
- [ ] ph5toms
- [ ] ph5tostationxml

Core
- [x] columns
- [x] cs2cs
- [x] decimate
- [ ] ebcdic
- [ ] experiment
- [x] external_file
- [ ] ibmfloat
- [ ] kef
- [ ] kefutility
- [ ] kefx
- [ ] mplturkey
- [x] ph5api
- [x] ph5utils
- [ ] pmonitor
- [ ] pn125
- [ ] pn130
- [ ] rt_130_h
- [ ] sac_h (maybe obsolete and need removal)
- [ ] sacfactory (maybe obsolete and need removal)
- [ ] sacreader (maybe obsolete and need removal)
- [ ] segd_h
- [ ] segdreader
- [ ] segy_h
- [ ] segyfactory
- [ ] segyreader
- [ ] sfactory
- [ ] timedoy

Utilities
- [ ] 125a2ph5
- [ ] 1302ph5
- [ ] changes
- [ ] cross_check_event_array_data
- [ ] csvtokef
- [ ] dumpfair
- [ ] dumpsac (Needs rewrite...use Obspy)
- [ ] dumpsgy
- [ ] fix_3chan_texan
- [ ] fix_num_samples
- [ ] geod2kef
- [ ] grao2ph5 (obsolete...remove)
- [ ] index_offset_t
- [ ] initialize_ph5
- [ ] kef2kml
- [ ] kef2ph5
- [ ] kefedit
- [ ] keftocsv
- [ ] load_das_t
- [ ] meta_data_gen
- [X] metadatatoph5
- [ ] noven
- [ ] novenkef
- [ ] novenqc
- [ ] novitiate (might be obsolete)
- [ ] nuke_tables
- [x] obspytoph5
- [ ] pforma_io
- [ ] pformacl
- [ ] pformagui
- [ ] ph5_help
- [ ] ph5_merge_helper
- [ ] ph5_total
- [ ] ph5validate
- [ ] segd_h
- [ ] recreate_external_references
- [ ] report2ph5
- [ ] report_gen
- [ ] resp_load
- [ ] seg2toph5
- [ ] segd2ph5
- [ ] segy2ph5
- [ ] set_deploy_pickup_times
- [ ] set_n_i_response
- [ ] sort_array_t
- [ ] sort_kef_gen
- [ ] tabletokef
- [ ] time_kef_gen
- [ ] unsimpleton
- [ ] watchit

**Comment by derick-hess** [comment]
@damhuonglan @dthomas1953 I think our highest priority should be the clients, ph5toms especially, and then ___toph5 programs.

**Comment by damhuonglan** [comment]
Anyone who are working unit test for a package should comment it on this issue so our works don't overlap each other. 
I currently working on ph5availability's unit test

**Comment by ascire-pic** [comment]
Appropriate unit tests are being created as changes are being implemented. As a result, I am closing this issue since unit tests are no longer being implemented as described in this issue.
