### ISSUE TITLE
[BUG] Test fcnt bad values

### ISSUE THREAD

**Issue by derick-hess** [PIC-IRIS/PH5#283]
**Describe the bug**
The current fcnt file I created for testing has randomly generated data.
I must have been sleepy when I generated the data because it contains impossible values.
For all the current unit tests, it works no problem, but ph5toms and most ph5to___ should fail trying to pack that data. I will create a good fcnt file needs to be created. Maybe this one should exist as well for testing graceful failure for impossible values.

**Comment by ascire-pic** [comment]
Good test data has been located and integrated into the testing environment.
