### ISSUE TITLE
[FEATURE] PH5 Magnetotellurics Metadata

### ISSUE THREAD

**Issue by derick-hess** [PIC-IRIS/PH5#289]
**Is your feature request related to a problem? Please describe.**
Add new metadata fields to capture magnetotelluric metadata not currently captured

channel:
Declination
Declination_epoch

response:
Contact_resistance
Length

**NEW tables**
Provenance table (for seismic and mt):
Creating_application
Creation_time

Creator
Email
Name
Organization
Organization_url

Submitter
Email
Name
Organization
organization_url

Software
Author
Email
Name
Organization
Organization_url
Name
Version
Release_date

.
calibrations table (maybe):
eX:
frequency
real
imaginary

eY:
frequency
real
imaginary

hX:
frequency
real
imaginary

hY:
frequency
real
imaginary

hZ:
frequency
real
imaginary

**Comment by derick-hess** [comment]
I'll format the above PR for easier viewing

**Comment by timronan** [comment]
This is being handled by  MTH5 https://mth5.readthedocs.io/en/tables/index.html and a different group.
