### ISSUE TITLE
PH5 Structure Documentation

### ISSUE THREAD

**Issue by nick-iris** [PIC-IRIS/PH5#305]
@derick-hess Would you be willing to help us write some additional documentation about the structure of PH5?

I think it would be helpful to have another page along side the [PH5 Structure wiki page](https://github.com/PIC-IRIS/PH5/wiki/PH5-Structure) that explains how the various tables in PH5 relate to one another.

Additionally there is no documentation describing how the Index_t table references the miniPH5_#####.ph5 files, and other details about the storage of timeseries. For example, I think there should be a paragraph describing how miniPH5_#####.ph5 files get split up within a PH5 experiment.

You know the most about the low level structure of PH5, so I think your help documenting would be invaluable to the project.

**Comment by derick-hess** [comment]
Sure I'll work on that. I'll also write a small programming tutorial. I think I will distill down what is in metadtatoph5 and obspytoph5 into a basic tutorial on taking both data and metadata and writing it into PH5.
