### ISSUE TITLE
ph5_validate falsely identifies stations as missing data

### ISSUE THREAD

**Issue by nick-iris** [PIC-IRIS/PH5#308]
**Describe the bug**
A few issues with PH5 validate.

1. It falsely marks stations that have data for not having data. For example, running
` ph5_validate -n master.ph5 -p /PH5_Experiments/pn4/16-015/ --level ERROR` incorrectly 
showed that every station was missing data.
2. It crashes on experiments with many miniPH5_#####.ph5, because there are too many open files. For example, running
`  ph5_validate -n master.ph5 -p /PH5_Experiments/pn4/16-015/ --level ERROR`
results in 
```
  File "H5F.c", line 604, in H5Fopen
    unable to open file
  File "H5Fint.c", line 992, in H5F_open
    unable to open file: time = Thu Jun 20 22:58:32 2019
, name = '/PH5_Experiments/pn4/16-015/miniPH5_00267.ph5', tent_flags = 0
  File "H5FD.c", line 993, in H5FD_open
    open failed
  File "H5FDsec2.c", line 339, in H5FD_sec2_open
    unable to open file: name = '/PH5_Experiments/pn4/16-015/miniPH5_00267.ph5', errno = 24, error message = 'Too many open files', flags = 0, o_flags = 0

End of HDF5 error back trace
```

**Comment by derick-hess** [comment]
Looks like you have a good fix for it. We fixed the bug in ph5_api, but missed adding the forget das calls to this.
