### ISSUE TITLE
[BUG] segdtoph5 not creating array table for multiple deployments

### ISSUE THREAD

**Issue by ascire-pic** [PIC-IRIS/PH5#320]
segdtoph5 did not create a complete array table for multiple deployments of nodes at the same station. 

Program Version: segdtoph5 2019.14
pforma 2019.14

Bug was noted in the Rutford Ice Stream experiment. Nodes were deployed at 15 stations on array 9 on Dec 11 for ~1 hour to record a shot. Different nodes were then redeployed at the same station IDs on array 9 on Dec 28 for ~10 hours. When segdtoph5 was run (both via pforma and via command line), the resulting array table only contained entries for 1 of the 2 deployments. For 10 nodes, only the Dec 11 deployment was listed, while for the other 5 only the Dec 28 deployment was in the array table.

Each station ID that was deployed twice has 2 fcnt files, one named 9050.0.0.fcnt, and one named 9050.1.0.fcnt, for the two deployments. Both files were added to the PH5 and all data was included in the PH5 in spite of the incomplete array tables.

Station IDs affected: Array 9, stations 9050 to 9064

Included here are the original array tables created by segdtoph5 in csv format (a9-orig.txt) and the modified array tables that were manually edited to include both deployments in Excel & csv format (a9-fixed.xlsx & a9-fixed.txt). In the Excel version of the fixed array table, rows that were added to the array table are highlighted green.

[a9-fixed.xlsx](https://github.com/PIC-IRIS/PH5/files/3448807/a9-fixed.xlsx)
[a9-fixed.txt](https://github.com/PIC-IRIS/PH5/files/3448814/a9-fixed.txt)

[a9-orig.txt](https://github.com/PIC-IRIS/PH5/files/3448808/a9-orig.txt)

Location of data files:
All Rutford Ice Stream files are on PASSCAL ph52 server
Original fcnt files: /ph52/Working/RutfordIceStream/RutfordIceStream-Zone17-NodeData/Other/9/
PH5 files created by pforma before merge: /ph52/Working/RutfordIceStream/Archive-PH5
Final version of PH5 with correct array tables: /ph52/Completed/19-004_RutfordIceStream/

**Comment by damhuonglan** [comment]
I checked with segdtoph5:
+ with 9050.0.0.fcnt, it created in array table data with deploy_time=Tue Dec 11 11:26:16 2018
+ with 9050.1.0.fcnt, it created in array table data with deploy_time=Fri Dec 28 18:28:44 2018
Although the deploy_time of the 2nd one is lightly different with your fix, I still think it is correct.
Nex step, I will check with pforma to see if anything wrong with that.

**Comment by damhuonglan** [comment]
@ascire-pic: I just push a commit for segdtoph5 that consider deploy time different when adding data to array table. However, there is an error in pforma when reading the raw data files which you seem not jump into it. I will see you on Monday to see what version you are using.

**Comment by damhuonglan** [comment]
So we should use files.rg16 which are more descriptive than files.fcnt. However when I run pforma with new segdtoph5, it creates double data for the fist station in the raw list file created.

**Comment by damhuonglan** [comment]
the reason that pforma duplicate data for the first station is the master.ph5 is copied to Sigma before adding other data which includes the data of the first station as well.
The above commit is a fix for this bug.
I will close this issue for now. You can reopen and give more comment if you see the problem still persist.

**Comment by derick-hess** [comment]
I haven't looked at the commits yet to see if this was fixed, but it looks like you just committed changes to a branch for a different pull request.

To fix issues, create a new branch based off master, make the changes, commit and push to new branch. After this open a new pull request.

[Hot to contribute](https://github.com/PIC-IRIS/PH5/blob/master/CONTRIBUTING.md)

**Comment by damhuonglan** [comment]
Thank you Derick. I already committed these changes to a new branch and create pull request for it.

 I just tried to commit too many things to remove_sys_exit. Is this possible for me to go back to a certain commit of remove_sys_exit that I already removed sys_exit and global variables from files and then try to merge that and move all other changes to a new branch?

**Comment by derick-hess** [comment]
Yes, you can do a `git revert` on the two commits on that branch then push and it should be back to where it was before.

**Comment by ascire-pic** [comment]
Issue appears to have been resolved in #341 

Test PH5 archive created using same data where problem was discovered has correct array tables for multiple deployments at a single station.
