### ISSUE TITLE
PH5 UI

### ISSUE THREAD

**Issue by dsentinel** [PIC-IRIS/PH5#327]
@derick-hess, I'm not sure what the new PH5 UI is called.
What is the current state?
Can dev on it be resumed?
Where does it live?

**Comment by derick-hess** [comment]
I'll look and find it. What it had done so far is copy UI elements from the other UI programs as well as had the start of a UI that looked as close to Nexus as possible for viewing and editing metadata within PH5.

**Comment by dsentinel** [comment]
Just a friendly ping @derick-hess
If you point me at it's last known location I can dig as well.
