### ISSUE TITLE
Unit test ground work and loggging

### ISSUE THREAD

**Issue by dsentinel** [PIC-IRIS/PH5#347]
Before the unit tests get expanded (which should be happening on all code changes),
I think these needs to be done:
- [ ] Remove all logging, stdout, stderr from current tests. That is they should be at least caught, and possibly asserted on
- [ ] Rework logging if necessary, and standardize the way it's used in all modules
- [ ] Move `create_ph5.sh` into the testing setup / fixtures
- [ ] Build the necessary scaffolding in unit tests to handle the above so all can use the fixtures/setup tear down, and catch logging.

**Comment by ascire-pic** [comment]
Issue is being closed due to shifting development efforts to GeoHDF.
