### ISSUE TITLE
[FEATURE] ph5tostationxml to complain about lat/lon/X/Y being out of bound

### ISSUE THREAD

**Issue by akram-pic** [PIC-IRIS/PH5#363]
**Is your feature request related to a problem? Please describe.**
ph5tostationxml requires locations (lat/lon==location/X/value_d, location/Y/value_d) to be in degree. It pulls this information from the array table, and currently if the values are not within bounds of +-90 and +-180 degree it throws out this cryptic message: "ph5.clients.ph5tostationxml - INFO: Request resulted in no data."
 
**Describe the solution you'd like**
ph5tostationxml to clearly complain about lat/lon/X/Y being out of bound; basically a more meaningful error message.

**Comment by damhuonglan** [comment]
Will need to add this check for ph5validate as well.
