### ISSUE TITLE
[BUG] ph5toms writes only one component

### ISSUE THREAD

**Issue by tjnewton** [PIC-IRIS/PH5#374]
**Describe the bug**
ph5toms does not write miniseed files for multiple components, even if the desired components are specified with the -c flag. 

**Environment**
 - OS: macOS 10.15.2
 - Program Version: PH5 4.1.3 (latest)

**To Reproduce**
`ph5toms -n master.ph5 -s 2018-03-13T00:00:00.00 -t 2018-03-13T23:59:59.99 -o mseed -F MSEED -c 1,2,3 --station_id 1`

**Expected behavior**
Should write mseed files for the three specified components 1, 2, and 3, or DP1, DP2, and DPZ. Instead a miniseed file for only the first component in the list is generated. If the -c flag is not included ph5toms writes only the first component. The behavior is the same for the --channel flag, and is independent of syntax, e.g., "-c 1,2,3" "-c=1,2,3" "-c DP1,DP2,DPZ" "--channel 1,2,3" "--channel=1,2,3" " --channel DP1,DP2,DPZ" all produce the same undesired result.

**Comment by nick-iris** [comment]
I also have observed this behavior in the `ph5toms` client. This needs to be fixed ASAP.

**Comment by tjnewton** [comment]
Thanks Nick!
