### ISSUE TITLE
[BUG] ph5toms generates miniseed files with multiple traces of duplicate data

### ISSUE THREAD

**Issue by tjnewton** [PIC-IRIS/PH5#375]
**Describe the bug**
ph5toms writes miniseed files with multiple traces containing different segments of the same data.

**Environment**
 OS: macOS 10.15.2
Program Version: PH5 4.1.3 (latest)

**To Reproduce**
`ph5toms -n master.ph5 -s 2018-03-13T00:00:00.00 -t 2018-03-14T23:59:59.99 -o mseed -F MSEED -c 1 --station_id 1`

**Expected behavior**
Should write miniseed files containing a single trace without duplicate data. Screenshot of plots and traces below show duplicate segment. 

**Screenshots**
<img width="1022" alt="Screen Shot 2020-01-28 at 2 09 48 PM" src="https://user-images.githubusercontent.com/54011699/73309886-01f81b80-41d8-11ea-8eea-19281311cada.png">

**Comment by ascire-pic** [comment]
Currently do not have enough information to follow up on this issue and nothing similar has been reported by other users. Based on that, I'm going to close the issue for now. Please re-open the issue and supply some example data to help track it down if the problem reoccurs.
