### ISSUE TITLE
Add wildcard support for Shot-ID and Shotline

### ISSUE THREAD

**Issue by nick-iris** [PIC-IRIS/PH5#39]
I've come to the conclusion that Shot-ID and Shotline should still accept wildcards even though shot-ids are not unique across shotlines.

**Comment by derick-hess** [comment]
Sounds good. I think it's a good practice to allow wild cards on as many parameters as we can for flexibility.

**Comment by nick-iris** [comment]
I agree.  I'm working on adding this to the ph5tomsAPI.py code now. I've already updated ph5toexml.py to accept wildcards for shotline and shotid. I'll push both once finished.
