### ISSUE TITLE
[BUG]segdtoph5 command line processing time per segment has increased

### ISSUE THREAD

**Issue by hrotman-pic** [PIC-IRIS/PH5#407]
**Describe the bug**
Last fall I added nearly 600 GB of 500 sps data to a PH5 with segdtoph5 command line and it took about 3 days.  In April I added ~480 GB of 250 sps data to a PH5 with segdtoph5 command line and it took nearly 11 days.  Both data sets had trace segments of 30 min and had no combining of traces.  The time did not appear to increase dramatically per file, but was consistently longer than I expected based on the append from last fall, for example: first segment added last fall took 0.2 s; first segment added in April took ~1.5 s.

**Environment (please complete the following information):**
 - OS: ph51, ph52
 - Program Version segdtoph5 2019.252

**Expected behavior**
Consistency in append with same version of the program.  These appends were run with the same version of segdtoph5, and the command line cannot multi-thread, so a quicker append is strongly preferred for efficiency in finishing the PH5 archive.

**Additional context**
A spreadsheet is attached with a partial comparison of append times and other potentially relevant information.
[segdtoph5_comparison_SHCZO-BASIN.xlsx](https://github.com/PIC-IRIS/PH5/files/4783118/segdtoph5_comparison_SHCZO-BASIN.xlsx)

**Comment by ascire-pic** [comment]
Current not reproducible; closing the issue report until the problem reoccurs
