### ISSUE TITLE
[BUG] ph5tostationxml outputs stationxml that is does not comply with the stationxml xsd schema

### ISSUE THREAD

**Issue by timronan** [PIC-IRIS/PH5#432]
**Describe the bug**
Ph5tostationxml outputs stationxml that is does not comply with the stationxml xsd schema. 

Specifically the field :
<Created>2020-10-08 21:58:09.039103</Created>

Is formatted incorrectly. 

It should at least have a T inbetween the day and hour, similar to:
<Created>2020-10-08T21:58:09.039103</Created>

This bug can be quickly addressed by changing the format
created=datetime.now() on line 955 clients.ph5tostationxml
to
created=datetime.now().isoformat(sep='T')
or 
created=datetime.now().strftime('%Y-%m-%dT%H:%M:%S')

**Environment (please complete the following information):**
 - OS: Centos 7
 - Program Version oph5tostationxml  Version: 2019.63

**To Reproduce**
run ph5tostationxml 
run the output stationxml document through the validator. 
**Expected behavior**
Output stationxml doucment should pass validation. 

**Additional context**
Issue started to occur after updating obspy. We should be explicit with our <Created> date times so we don't run into this issue.

**Comment by nick-falco** [comment]
@timronan I think the correct date string format should be:

```
'%Y-%m-%dT%H:%M:%S.%f'
```

Note the `.%f` at the end of the date string.

```
>>> from datetime import datetime
>>> created = datetime.now().strftime('%Y-%m-%dT%H:%M:%S.%f')
>>> print (created)
2020-10-09T11:47:25.525567
```

**Comment by timronan** [comment]
@nick-falco thanks for the catch.

**Comment by nick-falco** [comment]
Actually it may be better to use the Obspy UTCDateTime class instead and also put a "Z" at the end of the format string. I think the times should be in UTC.

**Comment by ascire-pic** [comment]
@timronan Are you planning to work on this issue?

**Comment by timronan** [comment]
@ascire-pic I can fix this issue but I need to finish all of my outstanding projects before I start on this one. There may be a delay before I can work on this patch.

**Comment by ascire-pic** [comment]
Sounds good! Was looking through the open issues and just wanted to check.

**Comment by gbbofh** [comment]
@timronan  I can start on a pull request to fix this if you haven't started working on it yet.

**Comment by timronan** [comment]
@gbbofh please start this PR. Thew fix seems to be outlined in this issue.

**Comment by gbbofh** [comment]
@timronan I should have a PR fixing this issue up later today.

**Comment by timronan** [comment]
@gbbofh sounds good. I will review the PR when it is posted.
