### ISSUE TITLE
/Experiment_g/Experiment_t/net_code_s

### ISSUE THREAD

**Issue by yazan-iris** [PIC-IRIS/PH5#447]
What is /Experiment_g/Experiment_t/net_code_s, I understand its the network code, what is the impact of missing such field in a document?

**Comment by nick-falco** [comment]
It's the FDSN network code. My guess is that the web service would fail on both metadata and data extraction if this was missing, but just a guess as I don't have the code in front of me. See the following document for column definitions of each table:

https://github.com/PIC-IRIS/PH5/wiki/PH5-Structure
