### ISSUE TITLE
Sort Table

### ISSUE THREAD

**Issue by yazan-iris** [PIC-IRIS/PH5#455]
What does it mean when Sort Table has many rows pointing to the same Array:

array.       |start time
-----------------------
Array-001|1506780000
Array-001|1506781800
.
.
.
.
.

**Comment by hrotman-pic** [comment]
As far as I know, this is expected and means that there are multiple recording windows for that datalogger and/or multiple dataloggers (which usually means multiple stations) in the array.

**Comment by hrotman-pic** [comment]
@yazan-iris based on the timestamp, the example you used is from 17-034.  Please email the PIC data group if you are seeing problems with PH5 17-034.
