### ISSUE TITLE
Receiver_Groups Data_a_xxx

### ISSUE THREAD

**Issue by ysuleiman** [PIC-IRIS/PH5#456]
Is the data in the Data_a_xxx table/dataset already decoded?  For example, do I need to Steim decoder?  My question is regarding the raw data and not the API.  So if I to extract the data, do I need to decode it.  Thanks

**Comment by timronan** [comment]
You likely will not need to do any decoding to access and manipulate Data_a_xxx table/datasets. The data sets are stored and extracted as int values and are seemingly not compressed.

Example:
```
import numpy as np
import h5py
timeseries = h5py.File('./PH5/ph5/test_data/ph5/miniPH5_00001.ph5', 'r')
timeseries['Experiment_g']['Receivers_g']['Das_g_12183']['Data_a_0001']
type(timeseries['Experiment_g']['Receivers_g']['Das_g_12183']['Data_a_0001'][0])
```
returns:
<HDF5 dataset "Data_a_0001": shape (3000,), type "<i4">
numpy.int32

Further documentation can be found here: http://davis.lbl.gov/Manuals/HDF5-1.8.7/UG/11_Datatypes.html
