### ISSUE TITLE
Remove mstoph5, metadatatoph5 from code stack

### ISSUE THREAD

**Issue by ascire-pic** [PIC-IRIS/PH5#486]
Reminder to remove mstoph5 and metadatatoph5 from the PH5 code stack as well as any remaining mentions in the documentation. Both programs are being removed due to a number of bugs/issues with functionality plus incompatibilities with other PH5 programs.

**Comment by timronan** [comment]
TODO: Remove these commands from the help page.

**Comment by timronan** [comment]
We want to update the cli commands `ms2ph5`, `metadata2ph5`, and `segy2ph5` to require users to add a flag called
`--FORCE` to run these commands. Additionally, we want to add a note to the top of the help documentation for each of these commands that states something similar to:

```
"Command_Name" is no longer supported by the PH5 software. Please use different functions to load reformat data as PH5. 
```
