### ISSUE TITLE
[BUG] segytoph5 throwing exceptions an not running

### ISSUE THREAD

**Issue by mike-iris** [PIC-IRIS/PH5#507]
**Describe the bug**
segytoph5 throwing exceptions an not running

**Environment (please complete the following information):**
 MacOS 12.6

**To Reproduce**
run in the regular git deployed configuration

**Expected behavior**
read a segy file and create a respective set ph5, master and miniPH5 files without metadata

**Screenshots**
n/a

**Additional context**
n/a

**Comment by timronan** [comment]
`segytoph5` is not currently being supported. The transformation between SEGY and a modern active source storage format maybe considered at a future date.

**Comment by timronan** [comment]
This code could be potentially removed from the PH5 software package. Refer to issue `https://github.com/PIC-IRIS/PH5/issues/348`.
