### ISSUE TITLE
ph5_validate: ph5.utilities.ph5validate - ERROR: list index out of range

### ISSUE THREAD

**Issue by emilylmaher** [PIC-IRIS/PH5#508]
**Describe the bug**
When running ph5_validate command run into the error that the list index is out of range.  

**Environment (please complete the following information):**
 - OS: PIC PH5 server, 
 - Program Version [ph5toms 2018.268]

**To Reproduce**
Run ph5_validate on any of the directories in validate_logs that is 24 bytes: 

- 10-008
- 10-021
- 15-015
- 11-021
- 16-019
- 17-028
- 16-014
- 16-015 - Pull the same error, but on list to be fixed
- 17-016 - Pull the same error, but on list to be fixed

**Expected behavior**
When you run ph5_validate after a bit the code will kick out the error: ph5.utilities.ph5validate - ERROR: list index out of range

**Screenshots**
_Taken from experiment 10-008_
<img width="1463" alt="Screenshot 2022-11-08 at 5 29 48 PM" src="https://user-images.githubusercontent.com/116837946/200706263-3575fca4-738d-43b3-a743-2c3f31c7603c.png">

**Comment by timronan** [comment]
This issue is resolved by PR #518. Thank you very much for making this update.
