### ISSUE TITLE
ph5tostationxml.py not correctly filtering data

### ISSUE THREAD

**Issue by nick-iris** [PIC-IRIS/PH5#8]
@rsdeazevedo  @derick-hess  When a request is made to ph5tostationxml.py the results are not filtered correctly. It seems that the service is only enforcing the query filters at one level. For example if a request is made for an unknown channel, then no channel information is displayed but station and network info is still displayed. **In this case no information should be displayed at all.**

Here are a few examples:

_**Still displays network and station info when a unknown channel is requested.**_
`python ph5tostationxml.py --basepath /hdf5-data2/PH5_Experiments/pn4/13-005/ -p /hdf5-data2/PH5_Experiments/pn4/13-005/ -n master.ph5 --level=channel  --station 1001,1002 --channel XXX`
_**Still displays network and station info when a unknown location is requested.**_
`python ph5tostationxml.py --basepath /hdf5-data2/PH5_Experiments/pn4/13-005/ -p /hdf5-data2/PH5_Experiments/pn4/13-005/ -n master.ph5 --level=channel  --station 1001,1002 --location XX`

**Comment by nick-iris** [comment]
If this is too difficult to do in the API I can check the request level and the contents of the inventory in the web service handler, before writing the inventory as StationXML. So it is a lower priority item at this point, but should ultimately be fixed for the ph5stationxml.py program to be correct.

**Comment by derick-hess** [comment]
I'll work on this today.
